FIxes to build routines. Tweaks to -showOptions

diff --git a/OpenJML/buildRelease b/OpenJML/buildRelease
--- a/OpenJML/buildRelease
+++ b/OpenJML/buildRelease
@@ -52,7 +52,8 @@ NAMEZ=openjml-${VERSION}.zip
 	cp -r ${ANNOTATIONS}/bin/* temp2
 	touch temp2/JMLRUNTIME_MARKER
 	## jmlruntime.jar has bin-runtime, the annotations, and the marker file JMLRUNTIME_MARKER
-	(cd temp2; jar -cf ../${TEMPJAR}/jmlruntime.jar . ) 
+	## If Java is incorrectly setup, the jar command fails - so we check it this first time
+	(cd temp2; jar -cf ../${TEMPJAR}/jmlruntime.jar . ) || exit 1
     cp ${TEMPJAR}/jmlruntime.jar ${UI}
 	rm -rf temp2
 	echo "   " jmlruntime.jar created
@@ -92,9 +93,9 @@ NAMEZ=openjml-${VERSION}.zip
 	echo "   " Creating jmlspecs.jar
 	## The jmlspecs.jar contains the composite Java 1.8 specs files
 	## The openjml.jar file contains the OpenJDK and OpenJML class files, and the specs directories, combined for each Java version
-	(cd temp/specs18; jar -cf ../../${TEMPJAR}/jmlspecs.jar . )
+	(cd temp/specs18; jar -cf ../../${TEMPJAR}/jmlspecs.jar . ) || exit 1
 	
-	(cd temp; jar xf ../jsmtlib.jar ; )
+	(cd temp; jar xf ../jsmtlib.jar ) || exit 1
 	cp -r bin-runtime/* temp
     cp -r ${ANNOTATIONS}/bin/* temp
     touch temp/JMLRUNTIME_MARKER
@@ -103,7 +104,7 @@ NAMEZ=openjml-${VERSION}.zip
 	echo "   " Creating openjml.jar
 	echo "Manifest-Version: 1.0" > temp2/manifest
 	echo "Main-Class: org.jmlspecs.openjml.Main" >> temp2/manifest
-	(cd temp; jar -cfm ../${TEMPJAR}/openjml.jar ../temp2/manifest . )
+	(cd temp; jar -cfm ../${TEMPJAR}/openjml.jar ../temp2/manifest . ) || exit 1
 	##cp ${TEMPJAR}/openjml.jar ../OpenJMLUI
 	echo "   " jmlspecs.jar openjml.jar created
 	
