Revising and refactoring tests

diff --git a/OpenJMLTest/unittests/runtests b/OpenJMLTest/unittests/runtests
--- a/OpenJMLTest/unittests/runtests
+++ b/OpenJMLTest/unittests/runtests
@@ -1,8 +1,12 @@
 #! /bin/bash
 
 ## This script runs the JUnit tests (directly, without using Eclipse)
-## It does so by running the Test.java program, after compiling all the
+## It does so by running the OpenJMLTestRunner.java program, which is an OpenJML_specific
+## JUnit-test runner, after compiling all the
 ## unit test drivers in OpenJMLTest/src/org/jmlspecs/openjmltest/testcases/
+
+## If the environmental variable COV is set, then coverage measurements are reported, and
+## are stored in the one coverage data file 'unit-$1' where $1 is the name of the first testcase listed in the command-line
 
 ## $R is the location of the directory containing this script, with
 ## $R/.. expected to be OpenJMLTest, which should be a sibling of OpenJML21
@@ -10,6 +14,7 @@
 R=$( cd $(dirname "$BASH_SOURCE") && pwd)
 ROOT=$R/../../OpenJML21
 TEST=$R/../../OpenJMLTest
+SOLVERS=$ROOT/../../Solvers
 JROOT=$R/../libs
 JUNIT="$JROOT/junit-4.13.2.jar:$JROOT/hamcrest-core-1.3.jar:$JROOT/junit-jupiter-api-5.5.2.jar:$JROOT/apiguardian-api-1.1.0.jar"
 NJAVAC=$ROOT/build/*/jdk/bin/javac
@@ -19,7 +24,6 @@ NJAVA=$ROOT/build/*/jdk/bin/java
 
 . $ROOT/setup-exports
 
-
 cd $R
 rm -f *.class
 CL=`echo $ROOT/build/*/jdk/modules/*  | grep -v META | sed -e "s/ /:/g"`
@@ -27,12 +31,12 @@ CP=".:../src:$JUNIT:$CL"
 
 OPTIONS="-Xlint:unchecked -Xdiags:verbose -Xlint:text-blocks"
 
-while ! NOJML= $NJAVAC $OPTIONS -cp $CP -p $ROOT/build/*-release/jdk/modules $EXPORTS Test.java  ../src/org/jmlspecs/openjmltest/*.java ../src/org/jmlspecs/openjmltest/testcases/*.java ; do
+while ! NOJML= $NJAVAC $OPTIONS -cp $CP -p $ROOT/build/*-release/jdk/modules $EXPORTS OpenJMLTestRunner.java  ../src/org/jmlspecs/openjmltest/*.java ../src/org/jmlspecs/openjmltest/testcases/*.java ; do
 
-   # Build can fail because of race conditions between compiles if so then multiple runtests are started at once
+   # Build can fail because of race conditions between compiles if multiple runtests are started at once -- just retry
    echo Build failed for $@
    sleep 10
 done
 
-## Now run the compiled Test progam
-( cd ..; OPENJML_ROOT="$ROOT/../../Solvers" $NJAVA $AGENT -cp unittests:src:$JUNIT $EXPORTS Test $@ 2>&1 )
+## Now run the compiled Test program -- stdout and stderr output are combined into one output
+( cd ..; OPENJML_ROOT="$SOLVERS" $NJAVA $AGENT -cp unittests:src:$JUNIT $EXPORTS OpenJMLTestRunner $@ 2>&1 )
