Fixed up coverage measurement; improved coverage of scanner tests

diff --git a/OpenJMLTest/Makefile b/OpenJMLTest/Makefile
--- a/OpenJMLTest/Makefile
+++ b/OpenJMLTest/Makefile
@@ -3,27 +3,29 @@ mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
 ## The following includes a terminating /
 mkfile_dir := $(dir $(mkfile_path))
 
-ROOT=${mkfile_dir}
+## The folder containing this Makefile, namely .../OpenJMLTest
+TEST=${mkfile_dir}
+
+## The folder containing the source and builds, namely (currently) .../OpenJML21
 D=OpenJML21
 
 ### The following is the OpenJML tests
 
 openjml-test: prep
 	-make jsontests
-	-time make unittests-par
-	-time make unittests-seq
+	-make unittests-par
 	-make scripttests
 	-make tutorial-tests
 	#( cd ./unittests; grep -v sleep ./runall | tr -d '&' > ./runseq ; source ./runseq )
 
 openjml-clean: .FORCE
-	(cd ${ROOT}/../$D; make clean version openjml jmlruntime.jar )
+	(cd ${TEST}/../$D; make clean version openjml jmlruntime.jar )
 
 openjml: .FORCE
-	(cd ${ROOT}/../$D; make version openjml jmlruntime.jar )
+	(cd ${TEST}/../$D; make version openjml jmlruntime.jar )
 
 release: .FORCE
-	(cd ${ROOT}/../$D; make release)
+	(cd ${TEST}/../$D; make release)
 
 T=temp-release
 
@@ -35,31 +37,40 @@ prep: .FORCE
 	echo "import org.jmlspecs.annotation.Pure; public class C { @Pure int m() { return 0; } }" > $T/C.java
 	echo "import org.jmlspecs.annotation.*; public class D { @Pure int m() { return 0; } }" > $T/D.java
 
-tutorial-tests: .FORCE
+tutorial-tests: Run.class .FORCE
 	@ ( echo Testing tutorial files ;\
-            alias openjml=$(mkfile_dir)/../OpenJML21/openjml ; \
-	    cd $(mkfile_dir)/../../openjml.github.io/tutorial; \
+	    . $(TEST)/setup-coverage tutorialtests ; \
+            alias openjml="$OJA" ; \
+	    cd ${TEST}/../../openjml.github.io/tutorial; \
 	    ./test \
 	)
 
-release-tests: .FORCE
+release-tests: Run.class .FORCE
 	@ echo Running release tests with current development build
-	@ NOZIP= $(ROOT)releaseTests/runtests > log-release-tests || ( echo "Errors reported in log-release-tests" && exit 1 )
+	@ NOZIP= $(TEST)releaseTests/runtests > log-release-tests || ( echo "Errors reported in log-release-tests" && exit 1 )
 
-unittests-seq:
-	@ $(ROOT)unittests/runseq
+unittests-seq: Run.class .FORCE
+	@ $(TEST)unittests/runseq
 			
-unittests-par:
-	( ${ROOT}/unittests/runpar | tee log-unittests | sort  )
+unittests-par: Run.class .FORCE
+	( ${TEST}/unittests/runpar | tee log-unittests | sort  )
 
-scripttests: .FORCE
-	( cd ${ROOT}/scripttests; ./escfiles-sort)
+scripttests: .FORCE Run.class
+	( cd ${TEST}/scripttests; ./escfiles-sort)
 
-jsontests: .FORCE
-	./scripttests/json/run
-	./scripttests/json-loc/run
+jsontests: .FORCE Run.class
+	${TEST}/scripttests/json/run
+	${TEST}/scripttests/json-loc/run
+
+Run.class:
+	$(TEST)/../OpenJML21/openjml-compile Run.java
+
 .FORCE:
 			
+version:
+	@ NOJML= njavac -d bin Version.java
+	@ STACK=X njava -cp bin Version
+
 ##### The following are debugging tests
 
 debug:
@@ -74,27 +85,27 @@ tests:
 test:
 	STACK=X njava -cp ../OpenJDKModule/runtime/src:libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar:libs/junit-jupiter-api-5.5.2.jar:libs/apiguardian-api-1.1.0.jar --add-modules jdk.compiler,java.base RunTests
 
-version:
-	@ NOJML= njavac -d bin Version.java
-	@ STACK=X njava -cp bin Version
-
-
+### The following are for coverage measurement
 
 cov-clean:
-	rm -rf $(ROOT)/cov
-	mkdir $(ROOT)/cov
+	rm -rf ${TEST}/cov
+	mkdir ${TEST}/cov
 
 cov-test:
-	COV= ./runpar
+	cd ${TEST}
+	COV= time ./unittests/runpar | tee log-unittests | sort
+	COV= time ./scripttests/escfiles-sort
+	COV= time make jsontests
+	##COV= time make tutorial-tests ## Not yet working and one does not complete
+	## COV= make release-tests ## Not yet working
 
 cov-report:
-	@rm -rf $(ROOT)/cov/html
-	@( cd $(ROOT); rm -f cov/combined.exec; java -jar ./jacoco/lib/jacococli.jar merge --quiet cov/*.exec --destfile cov/combined.exec )
-	@( cd $(ROOT); java -jar ./jacoco/lib/jacococli.jar report cov/combined.exec --html cov/html --quiet \
+	@rm -rf ${TEST}/cov/html
+	@( cd ${TEST}; rm -f cov/combined.exec; java -jar ./jacoco/lib/jacococli.jar merge --quiet cov/*.exec --destfile cov/combined.exec )
+	@( cd ${TEST}; java -jar ./jacoco/lib/jacococli.jar report --quiet cov/combined.exec --html cov/html \
             --sourcefiles ../OpenJML21/src/jdk.compiler/share/classes \
             --classfiles ../OpenJML21/build/macosx-x86_64-server-release/jdk/modules/java.base \
             --classfiles ../OpenJML21/build/macosx-x86_64-server-release/jdk/modules/jdk.compiler )
-	@make cov-show
 
 cov-show:
-	@open $(ROOT)/cov/html/index.html
+	@open ${TEST}cov/html/index.html
