Adding a prototype termination check and a warning category for missing measured_by clauses

diff --git a/OpenJMLTest/scripttests/json-loc/run b/OpenJMLTest/scripttests/json-loc/run
--- a/OpenJMLTest/scripttests/json-loc/run
+++ b/OpenJMLTest/scripttests/json-loc/run
@@ -36,6 +36,11 @@ diff xx/yy/Test.java.json Test.java.json.expected || ERR=1
 diff xx/yy/p/TestP.java.json TestP.java.json.expected || ERR=1
 diff xx/yy/q/r/TestPP.java.json TestPP.java.json.expected || ERR=1
 
+if [ $ERR == 1 ]; then echo "JSON LOCATION TESTS FAILED "; fi
+exit $ERR
+
+######## Not testing typed ASTs yet
+
 ## Typed AST
 echo TYPED
 rm -rf *.json
