Refactoring coverage testing and tests

diff --git a/OpenJML21/setup-exports b/OpenJML21/setup-exports
--- a/OpenJML21/setup-exports
+++ b/OpenJML21/setup-exports
@@ -1,6 +1,17 @@
-## source this file
+## This file sets OPENJML_EXPORTS, which contains a list of options stating which modules are to be exported.
+## These exports are needed when using OpenJML programmatically. OpenJDK itself was not designed with programmatic use
+## in mind, so all the internal APIs are fairly tightly encapsulated. This is infe for running OpenJML on the command-line
+## but is inadequate if internal ASTs etc are to be available when OpenJML is used programmatically.
 
-EXPORTS="\
+## These options are needed for the OpenJDK versions of both java and javac.
+
+## source this file
+if [ "$0" = "$BASH_SOURCE" ]; then
+    echo "Error: setup-exports script must be sourced"
+    exit 1
+fi
+
+OPENJML_EXPORTS="\
 --add-modules jdk.compiler,java.base \
 --add-exports=jdk.compiler/org.jmlspecs.openjml=ALL-UNNAMED  \
 --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
diff --git a/OpenJML21/setup-vars b/OpenJML21/setup-vars
--- a/OpenJML21/setup-vars
+++ b/OpenJML21/setup-vars
@@ -1,25 +1,30 @@
 # A sourced script that is shared between openjml and openjml-java
 
-# if OPENJML_INSTALL is not set, then set an d export it; otherwise just export the current value
-if [ -z ${OPENJML_INSTALL++} ]; then export OPENJML_INSTALL="$INSTALL" ; else export OPENJML_INSTALL ; fi
+## Uses $INSTALL
+## Sets BINJAVA BINJAVAC OPENJML_INSTALL OPENJML_SOLVERS OPENJML_SPECS
 
-# setup any profiling
-export PR=
-if [ -n "${PROF++}" ]; then
-  ## PROF is set to something
-  export PR=-agentpath:/Users/davidcok/profiler/lib/libasyncProfiler.dylib=start,event=cpu,file=profile.html
+if [ "$0" = "$BASH_SOURCE" ]; then
+    echo "Error: setup-vars script must be sourced"
+    exit 1
 fi
 
-## set BIN and other vars -- if those others are already set, then export them
-## BIN is an absolute path, still might have spaces
+# if OPENJML_INSTALL is not set, then set and export it; otherwise just export the current value
+if [ -z ${OPENJML_INSTALL++} ]; then export OPENJML_INSTALL="$INSTALL" ; else export OPENJML_INSTALL ; fi
+
+
+## set BINJAVA, BINJAVAC and other vars -- if those others are already set, then export them
+## BINJAVA and BINJAVAC are an absolute path, still might have spaces
+
 if [ -e "$INSTALL/version-info.txt" ]; then
   ## In a release
   if [ -n ${OPENJML_SOLVERS++} ]; then export OPENJML_SOLVERS ; fi
   if [ -n ${OPENJML_SPECS++} ]; then export OPENJML_SPECS ; fi
-  BIN="$INSTALL/jdk/bin/$1"
+  BINJAVA="$INSTALL/jdk/bin/java"
+  BINJAVAC="$INSTALL/jdk/bin/javac"
 else
   ## In development environment
   if [ -z ${OPENJML_SOLVERS++} ]; then export OPENJML_SOLVERS=$(realpath "$INSTALL"/../../Solvers) ; else export OPENJML_SOLVERS ; fi
   if [ -z ${OPENJML_SPECS++} ]; then export OPENJML_SPECS=$(realpath "$INSTALL"/../../Specs) ; else export OPENJML_SPECS ; fi
-  BIN=`echo "$INSTALL"/build/*/jdk/bin/$1`
+  BINJAVA=`echo "$INSTALL"/build/*/jdk/bin/java`
+  BINJAVAC=`echo "$INSTALL"/build/*/jdk/bin/javac`
 fi
diff --git a/OpenJMLTest/setup-coverage b/OpenJMLTest/setup-coverage
--- a/OpenJMLTest/setup-coverage
+++ b/OpenJMLTest/setup-coverage
@@ -1,20 +1,54 @@
 
+## Sets up coverage AND/OR profiling, depending on whether COV and PROF are set
+
+## Uses 
 
 ## Source this file
+if [ "$0" = "$BASH_SOURCE" ]; then
+    echo "Error: setup-coverage script must be sourced"
+    exit 1
+fi
+if [ -z "$1" ]; then
+    echo "script seup-coverage requires one argument"
+    exit 1;
+fi
 
-## Absolute path to the folder containing this file, which should be .../OpenJMLTest
+## The one argument provides the rootname of the $1.exec file, which will hold the coverage data
+
+## In order to obtain coverage data when running openjml, use $OJA as the executable.
+## The coverage agent ($AGENT) is a command-line option for 'java', whereas openjml is a version of 'javac'.
+## Consequently we have to run openjml programmatically, with the actual executable being a version of 'java', with the coverage agent attached.
+
+## $TEST is the absolute path to the folder containing this file, which should be .../OpenJMLTest
 FILE=$(realpath "$BASH_SOURCE" ) ## realpath needed to resolve symlinks -- result is the absolute path to this script file
-TEST=$(dirname "$FILE")
+TEST=$(dirname "$FILE") 
 
 if [ ! -e "$TEST/RunOpenJML.class" ]; then make -C "$TEST" RunOpenJML.class; fi
 
+INSTALL="$TEST"/../OpenJML21
+. "$INSTALL/setup-vars" ## uses INSTALL, sets BINJAVA
+
 export AGENT=
+export PR=
 export OJA="$TEST/../OpenJML21/openjml"
-if [ -n "${COV+set}" ]; then
+export OPENJML_JVM=
+
+## AGENT and PR are command-line arguments for **java**, not javac
+
+if [ -n "${COV++}" ]; then  ## Tests checks whether the variables are set, even if only to empty string
     # COV set, but may be empty
     mkdir -p "$TEST/cov"
     export AGENT="-javaagent:$TEST/jacoco/lib/jacocoagent.jar=destfile=$TEST/cov/$1.exec"
-    export OJA="$TEST/../OpenJML21/openjml-java -cp $TEST $AGENT RunOpenJML"
+    export OJA="$BINJAVA -cp .:$TEST $PR $AGENT RunOpenJML"
     ## FIXME - OJA above will not work with spaces in paths
+    export OPENJML_JVM="$AGENT"
 fi
 
+# setup any profiling -- $PR is a command-line argument for **java**, not javac
+if [ -n "${PROF++}" ]; then
+  ## PROF is set to something
+    export PR=-agentpath:/Users/davidcok/profiler/lib/libasyncProfiler.dylib=start,event=cpu,file=profile.html
+    export OJA="$BINJAVA -cp .:$TEST $PR $AGENT RunOpenJML"
+    ## FIXME - OJA above will not work with spaces in paths
+    export OPENJML_JVM="$AGENT $PR"
+fi
