Restoring literal : separators

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -15,6 +15,7 @@ name: Nightly test of OpenJML
 ## the other, shorter running, test suites.
 
 ## FIXME: The setting of PATH uses : where it might need ; for some OSes; it would be better if adjustments to PATH were not needed at all
+## FIXME: debug use of the $sep variable
 
 on:
   workflow_dispatch:
@@ -72,23 +73,25 @@ jobs:
 
     - name: Variable
       run: |
+        echo sep $sep
+        PATH="../../OpenJML/$FOLDER:$PATH" echo $PATH
         echo "failures= " >> $GITHUB_ENV
 
     - name: Run release tests
       run: |
-        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
+        PATH="../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
 
     - name: Run tutorial tests
       run: |
-        PATH="../../OpenJML/$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV
+        PATH="../../OpenJML/$FOLDER:$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV
 
     - name: Run json tests
       run: |
-        PATH="../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
+        PATH="../../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
 
     - name: Run userguide tests
       run: |
-        PATH="../../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
+        PATH="../../../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
 
     - name: Report
       run: |
@@ -124,6 +127,6 @@ jobs:
 
     - name: Run unit tests
       run: |
-        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest unittests-par 
+        PATH="../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest unittests-par 
 
 
