Fix failure message in workflow

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -72,26 +72,28 @@ jobs:
 
     - name: Variable
       run: |
-        export failures=""
+        echo 'failures=""' >> $GITHUB_ENV
 
     - name: Run release tests
       run: |
-        PATH="../../$FOLDERsep$PATH" make -C OpenJML/OpenJMLTest release-tests || export failures="$failures release tests failed\n"
+        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
         echo "FAILURE STRING" $failures
 
     - name: Run tutorial tests
       run: |
-        PATH="../../OpenJML/$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || export failures="$failures tutorial tests failed"
+        PATH="../../OpenJML/$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV
         echo "FAILURE STRING" $failures
 
     - name: Run json tests
       run: |
-        PATH="../../../$FOLDERsep$PATH" make -C OpenJML/OpenJMLTest json-tests || export failures="$failures json tests failed\n"
+        echo "FAILURE STRING" $failures
+        PATH="../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
         echo "FAILURE STRING" $failures
 
     - name: Run userguide tests
       run: |
-        PATH="../../../../$FOLDERsep$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || export failures="$failures userguide tests failed"
+        echo "FAILURE STRING" $failures
+        PATH="../../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
         echo "FAILURE STRING" $failures
 
     - name: Report
