Separation character experiments in workflow

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -73,25 +73,26 @@ jobs:
 
     - name: Variable
       run: |
-        echo sep $sep
-        PATH="../../OpenJML/$FOLDER:$PATH" echo $PATH
+        echo $sep $sepsemi
+        PATH="../../OpenJML/$FOLDER$sep$PATH" echo $PATH
+        PATH="../../OpenJML/$FOLDER$sepsemi$PATH" echo $PATH
         echo "failures= " >> $GITHUB_ENV
 
     - name: Run release tests
       run: |
-        PATH="../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
+        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
 
     - name: Run tutorial tests
       run: |
-        PATH="../../OpenJML/$FOLDER:$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV
+        PATH="../../OpenJML/$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV
 
     - name: Run json tests
       run: |
-        PATH="../../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
+        PATH="../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
 
     - name: Run userguide tests
       run: |
-        PATH="../../../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
+        PATH="../../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest userguide-tests-released || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
 
     - name: Report
       run: |
@@ -127,6 +128,6 @@ jobs:
 
     - name: Run unit tests
       run: |
-        PATH="../../$FOLDER:$PATH" make -C OpenJML/OpenJMLTest unittests-par 
+        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest unittests-par 
 
 
