Debugging nightly.yml

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -78,6 +78,10 @@ jobs:
         PATH="../../OpenJML/$FOLDER$sepsemi$PATH" echo $PATH
         echo "failures= " >> $GITHUB_ENV
 
+    - name: Run userguide tests
+      run: |
+        PATH="../../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest userguide-tests-nightly || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
+
     - name: Run release tests
       run: |
         PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV
@@ -89,10 +93,6 @@ jobs:
     - name: Run json tests
       run: |
         PATH="../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV
-
-    - name: Run userguide tests
-      run: |
-        PATH="../../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest userguide-tests || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV
 
     - name: Report
       run: |
